name: servblu
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.8.3
  flutter_local_notifications: ^18.0.1
  go_router: ^14.7.2
  validators: ^3.0.0
  firebase_core: ^3.12.0
  firebase_messaging: ^15.2.3
  flutter_masked_text2: ^0.9.1
  shared_preferences: ^2.5.2
  intl: ^0.20.2
  image_picker: ^1.1.2
  path: ^1.9.0
  google_sign_in: ^6.3.0
  hugeicons: ^0.0.7
  uuid: ^3.0.7
  table_calendar: ^3.0.9
  email_validator: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon_app.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo_foreground.png"

flutter:
  uses-material-design: true
  assets:
    - assets/inicial_image.png
    - assets/login.png
    - assets/google_icon.png
    - assets/forgot_password_image.png
    - assets/home_image.jpg
    - assets/second_image.png
    - assets/offer_image.png