// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzW7R-W8kFWjjfAUJrcvGnOQ0e3R-kT5I',
    appId: '1:957132089666:web:13ab823f36f6141d4340db',
    messagingSenderId: '957132089666',
    projectId: 'servblu-test',
    authDomain: 'servblu-test.firebaseapp.com',
    storageBucket: 'servblu-test.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcxyymzn6j05-QiW6BQ2xHezxeyfUjEIk',
    appId: '1:957132089666:android:49c2202ad4aeb6834340db',
    messagingSenderId: '957132089666',
    projectId: 'servblu-test',
    storageBucket: 'servblu-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1nCioDPxAofcsbYQwvANbOGgbFmT5LCM',
    appId: '1:957132089666:ios:35810a5ccee7b0a24340db',
    messagingSenderId: '957132089666',
    projectId: 'servblu-test',
    storageBucket: 'servblu-test.firebasestorage.app',
    iosBundleId: 'com.example.servblu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1nCioDPxAofcsbYQwvANbOGgbFmT5LCM',
    appId: '1:957132089666:ios:35810a5ccee7b0a24340db',
    messagingSenderId: '957132089666',
    projectId: 'servblu-test',
    storageBucket: 'servblu-test.firebasestorage.app',
    iosBundleId: 'com.example.servblu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzW7R-W8kFWjjfAUJrcvGnOQ0e3R-kT5I',
    appId: '1:957132089666:web:989729a1d7e7d5cb4340db',
    messagingSenderId: '957132089666',
    projectId: 'servblu-test',
    authDomain: 'servblu-test.firebaseapp.com',
    storageBucket: 'servblu-test.firebasestorage.app',
  );
}
