// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN4BvcFCpOf6XR1AHaFyr_LAtMtBXhkgg',
    appId: '1:365706756084:web:48a6f5142e2402e8b843a1',
    messagingSenderId: '365706756084',
    projectId: 'servblu-d9b69',
    authDomain: 'servblu-d9b69.firebaseapp.com',
    storageBucket: 'servblu-d9b69.firebasestorage.app',
    measurementId: 'G-H35XSGSTG8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_6NtFOMew9IWc7qFhHspO4tjZHkPHkuE',
    appId: '1:365706756084:android:7397d16540906becb843a1',
    messagingSenderId: '365706756084',
    projectId: 'servblu-d9b69',
    storageBucket: 'servblu-d9b69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeztexykn-HiVVpreu9TfYYIvlFfj8ces',
    appId: '1:365706756084:ios:c12ff4e3852bd9bab843a1',
    messagingSenderId: '365706756084',
    projectId: 'servblu-d9b69',
    storageBucket: 'servblu-d9b69.firebasestorage.app',
    iosBundleId: 'com.example.servblu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeztexykn-HiVVpreu9TfYYIvlFfj8ces',
    appId: '1:365706756084:ios:c12ff4e3852bd9bab843a1',
    messagingSenderId: '365706756084',
    projectId: 'servblu-d9b69',
    storageBucket: 'servblu-d9b69.firebasestorage.app',
    iosBundleId: 'com.example.servblu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBN4BvcFCpOf6XR1AHaFyr_LAtMtBXhkgg',
    appId: '1:365706756084:web:ad434da2375f5fbdb843a1',
    messagingSenderId: '365706756084',
    projectId: 'servblu-d9b69',
    authDomain: 'servblu-d9b69.firebaseapp.com',
    storageBucket: 'servblu-d9b69.firebasestorage.app',
    measurementId: 'G-C8662VM2EC',
  );

}