name: Deploy Notification Function

on:
  push:
    branches:
      - eric_feature

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Supabase CLI
      run: |
        curl -sSL https://github.com/supabase/cli/releases/latest/download/supabase_$(uname -s | tr '[:upper:]' '[:lower:]')_amd64.deb -o supabase.deb
        sudo dpkg -i supabase.deb
        sudo apt-get install -f  # Para instalar dependências ausentes

    - name: Deploy Function
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      run: supabase functions deploy send-notification --no-verify-jwt
